#  pnpm-workspace.yaml文件可以帮助你定义工作区的范围以及一些全局配置
#   1. 定义工作区范围：指定哪些包或目录属于这个工作区。
#   2. 包管理优化：可以共享依赖包，减少重复安装，提高安装速度和效率。
#   3. 跨包依赖：支持工作区内包之间的引用和依赖关系

# 下面配置表示工作区包含packages目录下的所有包，共享依赖包，并且支持跨包依赖。

packages:
  - "packages/*"